#line 2 "/home/lighthouse/CatDB/sql/parser/sql_scanner.cpp"

#line 4 "/home/lighthouse/CatDB/sql/parser/sql_scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer CatDB_FlexLexer
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* %if-c++-only */
/* begin standard C++ headers. */
#include <iostream> 
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */
/* %endif */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* %not-for-header */

/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern yy_size_t yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
/* %endif */

/* %if-c++-only */
	std::istream* yy_input_file;
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %if-not-reentrant */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */
/* %if-not-reentrant */
/* %not-for-header */

/* %ok-for-header */

/* %endif */
/* %endif */

void *CatDB_alloc (yy_size_t  );
void *CatDB_realloc (void *,yy_size_t  );
void CatDB_free (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG

typedef unsigned char YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int SqlScanner::yylex()

/* %if-c-only Standard (non-C++) definition */
/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;

/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 146
#define YY_END_OF_BUFFER 147
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[467] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  147,  146,
      142,  146,  121,  130,  110,  111,  117,  115,  112,  116,
      113,  118,  143,  114,   16,   15,   14,  146,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  139,  129,  122,  146,  138,  131,  146,  141,
      140,  142,   11,  120,  143,    0,  143,  143,    0,   17,
       12,   13,  145,  144,  144,  144,   25,  144,  144,  144,
       27,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,

      144,  144,   50,   21,   22,  144,  144,  144,  144,  144,
      144,  144,   61,    8,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  129,  128,  126,  127,
      123,  125,  124,  138,  137,  135,  136,  132,  134,  133,
      141,    0,  119,    0,    0,  143,  145,   24,  144,    9,
       23,   26,  144,  144,  144,  144,  144,  144,  144,  144,
      109,  144,  144,  144,  144,  144,  144,  144,  144,  144,
       96,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,   54,  144,  144,  144,

      144,  144,  144,  144,  144,  144,   10,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,   68,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,   76,  144,  144,  144,    0,  143,    0,  143,
      144,  144,  144,  144,    1,   92,   87,  144,  144,  144,
       33,  144,  144,   36,  144,  144,   40,   41,   95,  144,
      144,  144,  144,  144,  144,  144,   45,   46,  144,  144,
      144,  144,  144,  144,  144,   55,   56,   49,  144,   57,
       18,  144,  107,  144,  144,  144,    2,  144,  144,  144,
      144,  144,  144,   86,  144,  144,  144,  144,   69,   70,

      144,  144,  144,  144,   94,   91,  144,    4,  144,  144,
      144,  144,  144,  144,   93,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,    3,  106,   44,   47,  144,   52,  144,
       53,  144,  144,  144,   58,  144,  144,  144,  144,  144,
       62,  144,  144,  144,   64,   65,  144,  144,  144,  108,
      144,  144,   73,  144,  144,    6,  144,  144,  144,  144,
      144,  144,   79,  144,  144,   83,   88,   28,   30,  144,
      144,  144,   35,  144,  144,   39,  104,    5,   42,  144,
       48,  105,   51,  144,  144,  144,   59,  144,   60,  144,

      144,  144,  144,  144,   66,   67,  144,   71,   72,   74,
      144,  144,   75,  144,   99,   77,  144,  144,   20,   19,
       29,  144,  144,   84,  144,  144,   43,  144,  100,  144,
      144,   85,  102,  144,  144,   97,  144,  144,   80,  144,
      144,   78,   31,   34,   37,   38,  144,  144,  144,  101,
      144,   81,  144,   98,  144,   32,    7,   82,  144,  144,
       90,   89,  103,  144,   63,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    1,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,   16,   17,
       18,   19,    1,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
        1,   47,    1,    1,   48,   49,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,   70,   71,   72,   73,
       74,   75,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[76] =
    {   0,
        1,    1,    2,    1,    3,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    1,    1,    1,    1,    1,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    2,    6,    7,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6
    } ;

static yyconst flex_int16_t yy_base[478] =
    {   0,
        0,    0,   73,   74,   77,   78,   79,   82,  331,  969,
       84,  311,  969,  969,  969,  969,  220,  969,  969,  969,
      218,  221,   76,  969,   74,  969,  209,    0,   71,   69,
      114,  162,   75,  134,   50,   87,  131,   76,   83,   93,
       90,  115,  135,  138,   94,  182,  226,  185,  185,  139,
      133,    0,  969,    0,  969,  223,    0,  969,  247,    0,
      969,   93,  969,  969,  213,  215,  216,  243,   85,  969,
      969,  969,    0,    0,  135,  251,  157,  153,  181,  175,
        0,  221,  243,  233,  246,  235,  239,  280,  243,  258,
      270,  286,  270,  291,  294,  281,  295,  286,  287,  292,

      291,  285,    0,  334,    0,  304,  303,  340,  336,  330,
      317,  339,    0,  351,  338,  342,  170,  357,  352,  337,
      348,  353,  347,  338,  367,  359,  373,  390,  390,  385,
      375,  392,  400,  400,  394,  402,    0,  969,  969,  969,
      969,  969,  969,    0,  969,  969,  969,  969,  969,  969,
        0,   87,  969,  162,  153,  147,    0,    0,  396,    0,
        0,    0,  386,  401,  410,  401,  409,  397,  395,  416,
        0,  417,  410,  415,  420,  406,  427,  415,  420,  445,
        0,  444,  449,  437,  445,  440,  450,  462,  451,  453,
      445,  458,  463,  460,  465,  466,  469,  458,  461,  471,

      456,  472,  469,  475,  472,  472,    0,  471,  478,  506,
      507,  513,  512,  503,  508,  513,  513,  507,  519,    0,
      502,  521,  515,  519,  509,  518,  517,  527,  508,  529,
      520,  535,  110,  517,  545,  552,  139,  131,   98,   91,
      514,  537,  531,  551,    0,    0,    0,  559,  553,  573,
      558,  566,  560,  563,  573,  571,    0,    0,    0,  570,
      569,  566,  586,  583,  585,  570,    0,    0,  575,  578,
      569,  582,  578,  579,  582,    0,    0,    0,  594,    0,
        0,  585,    0,  585,  606,  622,    0,  623,  612,  613,
      621,  631,  636,    0,  618,  635,  628,  638,    0,    0,

      630,  623,  637,  639,    0,  626,  638,    0,  634,  629,
      647,  645,  642,  644,    0,  649,  637,  659,  662,  660,
      672,  683,  688,  682,  693,  690,  687,  683,  693,  694,
      680,  682,  693,    0,    0,    0,    0,  696,    0,  699,
        0,  685,  687,  693,    0,  695,  684,  687,  694,  704,
      711,  707,  702,  709,    0,    0,  735,  723,  735,    0,
      727,  728,  730,  732,  739,    0,  749,  754,  744,  738,
      744,  758,    0,  755,  747,    0,    0,  743,    0,  744,
      751,  753,    0,  764,  764,    0,    0,    0,    0,  754,
        0,    0,    0,  765,  764,  765,    0,  759,    0,  776,

      776,  793,  782,  797,    0,    0,  790,    0,    0,    0,
      804,  787,    0,  791,    0,    0,  810,  794,    0,    0,
        0,  808,  809,    0,  810,  796,    0,  814,    0,  804,
      810,    0,    0,  808,  809,    0,  802,  810,    0,  816,
      807,    0,  807,    0,    0,    0,  808,  809,  812,    0,
      826,    0,  821,    0,  813,    0,    0,    0,  851,  840,
        0,    0,    0,  840,    0,  969,  909,  916,  923,   84,
      926,  932,  939,  946,  953,  960,  962
    } ;

static yyconst flex_int16_t yy_def[478] =
    {   0,
      466,    1,  467,  467,  468,  468,  469,  469,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  470,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  466,  472,  466,  473,  474,  466,  475,  476,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  477,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,

      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  472,  466,  466,  466,
      466,  466,  466,  474,  466,  466,  466,  466,  466,  466,
      476,  466,  466,  466,  466,  466,  477,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,

      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  466,  466,  466,  466,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,

      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,

      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,  471,  471,  471,  471,  471,
      471,  471,  471,  471,  471,    0,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466
    } ;

static yyconst flex_int16_t yy_nxt[1045] =
    {   0,
       10,   11,   11,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,   52,   52,   52,   10,   52,   53,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   52,   52,   10,   10,   55,   55,   10,
       10,   10,   58,   58,   10,   62,   62,  101,   67,   73,
       68,   70,   71,   78,   62,   62,  155,   79,  237,  156,

       69,  238,   75,   80,   76,  240,   93,  102,   94,   77,
      106,  107,  240,   81,  110,  117,  101,  108,   95,   56,
       56,  109,   78,   59,   59,   10,   79,   61,   10,   69,
       61,   75,   80,   76,   82,   93,  102,   94,   77,  106,
      107,   83,   81,  110,  117,  238,  108,   95,   84,  111,
      109,   85,   86,  238,   96,  112,  103,  311,  115,  135,
      136,  156,   97,   82,  104,   98,  158,  156,  113,  105,
       83,   99,  114,  239,  100,  116,  240,   84,  111,  162,
       85,   86,   87,   96,  112,  103,   88,  115,  135,  136,
       89,   97,  163,  104,   98,  158,   90,  113,  105,   91,

       99,  114,   92,  100,  116,  128,  118,  164,  162,  166,
      119,   87,  129,  130,  165,   88,  120,  214,  132,   89,
      133,  163,  131,  134,  153,   90,   72,   65,   91,   66,
       65,   92,   65,   64,  128,  118,  164,  152,  166,  119,
      154,  129,  130,  165,  139,  120,  121,  132,  140,  133,
      122,  131,  134,  123,  124,   67,  141,   68,  125,  167,
      142,  126,  143,  168,  169,  127,  152,   69,  146,  154,
      170,  159,  147,  139,  160,  121,  171,  140,  172,  122,
      148,  176,  123,  124,  149,  141,  150,  125,  167,  142,
      126,  143,  168,  169,  127,  161,   69,  146,  177,  170,

      159,  147,  173,  160,  178,  171,  179,  172,  180,  148,
      176,  174,  186,  149,  181,  150,  183,  182,  175,  187,
      188,  189,  184,  190,  161,  191,  192,  177,   63,  185,
      466,  173,  198,  178,  199,  179,  466,  180,  466,  466,
      174,  186,  466,  181,  466,  183,  182,  175,  187,  188,
      189,  184,  190,  205,  191,  192,  207,  193,  185,  194,
      200,  198,  206,  199,  208,  201,  202,  195,  203,  204,
      209,  210,  196,  197,  211,  212,  213,  215,  216,  217,
      218,  221,  205,  222,  219,  207,  193,  223,  194,  200,
      224,  206,  220,  225,  201,  202,  195,  203,  204,  209,

      210,  196,  197,  211,  212,  213,  215,  216,  217,  218,
      221,  226,  222,  219,  227,  230,  223,  228,  229,  224,
      231,  220,  225,  232,  233,  234,  236,  241,  242,  243,
      244,  235,  245,  246,  247,  248,  249,  250,  252,  253,
      226,  251,  254,  227,  230,  255,  228,  229,  256,  231,
      257,  258,  232,  233,  234,  236,  241,  242,  243,  244,
      235,  245,  246,  247,  248,  249,  250,  252,  253,  259,
      251,  254,  260,  261,  255,  262,  263,  256,  264,  257,
      258,  265,  266,  267,  268,  269,  270,  271,  272,  273,
      274,  277,  278,  275,  279,  280,  281,  282,  259,  283,

      284,  260,  261,  276,  262,  263,  285,  264,  286,  287,
      265,  266,  267,  268,  269,  270,  271,  272,  273,  274,
      277,  278,  275,  279,  280,  281,  282,  288,  283,  284,
      289,  290,  276,  291,  292,  285,  293,  286,  287,  294,
      295,  296,  297,  298,  299,  300,  301,  302,  303,  304,
      305,  306,  307,  308,  309,  310,  288,  312,  317,  289,
      290,  318,  291,  292,  319,  293,  313,  314,  294,  295,
      296,  297,  298,  299,  300,  301,  302,  303,  304,  305,
      306,  307,  308,  309,  310,  315,  312,  317,  320,  316,
      318,  321,  322,  319,  323,  313,  314,  324,  325,  326,

      327,  328,  329,  330,  331,  332,  333,  334,  335,  336,
      337,  338,  339,  340,  315,  341,  342,  320,  316,  343,
      321,  322,  344,  323,  345,  346,  324,  325,  326,  327,
      328,  329,  330,  331,  332,  333,  334,  335,  336,  337,
      338,  339,  340,  347,  341,  342,  348,  349,  343,  350,
      351,  344,  352,  345,  346,  353,  354,  355,  356,  357,
      358,  359,  360,  363,  364,  361,  365,  366,  367,  370,
      371,  372,  347,  373,  368,  348,  349,  362,  350,  351,
      369,  352,  374,  375,  353,  354,  355,  356,  357,  358,
      359,  360,  363,  364,  361,  365,  366,  367,  370,  371,

      372,  376,  373,  368,  377,  378,  362,  379,  380,  369,
      381,  374,  375,  382,  383,  384,  385,  386,  387,  388,
      389,  390,  391,  392,  393,  394,  395,  396,  397,  398,
      376,  399,  400,  377,  378,  401,  379,  380,  402,  381,
      403,  404,  382,  383,  384,  385,  386,  387,  388,  389,
      390,  391,  392,  393,  394,  395,  396,  397,  398,  405,
      399,  400,  406,  407,  401,  408,  409,  402,  410,  403,
      404,  411,  412,  413,  414,  415,  416,  417,  418,  419,
      420,  421,  422,  423,  424,  425,  426,  427,  405,  428,
      429,  406,  407,  430,  408,  409,  431,  410,  432,  433,

      411,  412,  413,  414,  415,  416,  417,  418,  419,  420,
      421,  422,  423,  424,  425,  426,  427,  434,  428,  429,
      435,  436,  430,  437,  438,  431,  439,  432,  433,  440,
      441,  442,  443,  444,  445,  446,  447,  448,  449,  450,
      451,  452,  453,  454,  455,  456,  434,  457,  458,  435,
      436,  459,  437,  438,  460,  439,  461,  462,  440,  441,
      442,  443,  444,  445,  446,  447,  448,  449,  450,  451,
      452,  453,  454,  455,  456,  463,  457,  458,  464,  465,
      459,  466,  466,  460,  466,  461,  462,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,

      466,  466,  466,  466,  463,  466,  466,  464,  465,   54,
       54,   54,   54,   54,   54,   54,   57,   57,   57,   57,
       57,   57,   57,   60,   60,   60,   60,   60,   60,   60,
       74,   74,  137,  466,  466,  137,  137,  137,  137,  138,
      138,  138,  138,  138,  138,  138,  144,  466,  144,  466,
      144,  144,  144,  145,  145,  145,  145,  145,  145,  145,
      151,  466,  151,  151,  151,  151,  157,  157,    9,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,

      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466
    } ;

static yyconst flex_int16_t yy_chk[1045] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    3,    4,    5,
        6,    7,    5,    6,    8,   11,   11,   35,   23,  470,
       23,   25,   25,   30,   62,   62,   69,   30,  152,   69,

       23,  152,   29,   30,   29,  240,   33,   36,   33,   29,
       38,   39,  239,   30,   41,   45,   35,   40,   33,    3,
        4,   40,   30,    5,    6,    7,   30,    7,    8,   23,
        8,   29,   30,   29,   31,   33,   36,   33,   29,   38,
       39,   31,   30,   41,   45,  238,   40,   33,   31,   42,
       40,   31,   31,  237,   34,   42,   37,  233,   44,   50,
       51,  156,   34,   31,   37,   34,   75,  155,   43,   37,
       31,   34,   43,  154,   34,   44,  154,   31,   42,   77,
       31,   31,   32,   34,   42,   37,   32,   44,   50,   51,
       32,   34,   78,   37,   34,   75,   32,   43,   37,   32,

       34,   43,   32,   34,   44,   48,   46,   79,   77,   80,
       46,   32,   48,   48,   79,   32,   46,  117,   49,   32,
       49,   78,   48,   49,   66,   32,   27,   65,   32,   22,
       67,   32,   21,   17,   48,   46,   79,   65,   80,   46,
       67,   48,   48,   79,   56,   46,   47,   49,   56,   49,
       47,   48,   49,   47,   47,   68,   56,   68,   47,   82,
       56,   47,   56,   83,   84,   47,   65,   68,   59,   67,
       85,   76,   59,   56,   76,   47,   86,   56,   87,   47,
       59,   89,   47,   47,   59,   56,   59,   47,   82,   56,
       47,   56,   83,   84,   47,   76,   68,   59,   90,   85,

       76,   59,   88,   76,   91,   86,   92,   87,   93,   59,
       89,   88,   96,   59,   94,   59,   95,   94,   88,   97,
       98,   99,   95,  100,   76,  101,  102,   90,   12,   95,
        9,   88,  106,   91,  107,   92,    0,   93,    0,    0,
       88,   96,    0,   94,    0,   95,   94,   88,   97,   98,
       99,   95,  100,  110,  101,  102,  111,  104,   95,  104,
      108,  106,  110,  107,  111,  108,  109,  104,  109,  109,
      112,  112,  104,  104,  114,  115,  116,  118,  119,  120,
      121,  123,  110,  124,  122,  111,  104,  125,  104,  108,
      126,  110,  122,  127,  108,  109,  104,  109,  109,  112,

      112,  104,  104,  114,  115,  116,  118,  119,  120,  121,
      123,  128,  124,  122,  129,  131,  125,  130,  130,  126,
      132,  122,  127,  133,  134,  135,  136,  159,  163,  164,
      165,  135,  166,  167,  168,  169,  170,  172,  173,  174,
      128,  172,  175,  129,  131,  176,  130,  130,  177,  132,
      178,  179,  133,  134,  135,  136,  159,  163,  164,  165,
      135,  166,  167,  168,  169,  170,  172,  173,  174,  180,
      172,  175,  182,  183,  176,  184,  185,  177,  186,  178,
      179,  187,  188,  189,  190,  191,  192,  193,  194,  195,
      196,  198,  199,  197,  200,  201,  202,  203,  180,  204,

      205,  182,  183,  197,  184,  185,  206,  186,  208,  209,
      187,  188,  189,  190,  191,  192,  193,  194,  195,  196,
      198,  199,  197,  200,  201,  202,  203,  210,  204,  205,
      210,  211,  197,  212,  213,  206,  214,  208,  209,  215,
      216,  217,  218,  219,  221,  222,  223,  224,  225,  226,
      227,  228,  229,  230,  231,  232,  210,  234,  241,  210,
      211,  242,  212,  213,  243,  214,  235,  235,  215,  216,
      217,  218,  219,  221,  222,  223,  224,  225,  226,  227,
      228,  229,  230,  231,  232,  236,  234,  241,  244,  236,
      242,  248,  249,  243,  250,  235,  235,  251,  252,  253,

      254,  255,  256,  260,  261,  262,  263,  264,  265,  266,
      269,  270,  271,  272,  236,  273,  274,  244,  236,  275,
      248,  249,  279,  250,  282,  284,  251,  252,  253,  254,
      255,  256,  260,  261,  262,  263,  264,  265,  266,  269,
      270,  271,  272,  285,  273,  274,  286,  288,  275,  289,
      290,  279,  291,  282,  284,  292,  293,  295,  296,  297,
      298,  301,  302,  304,  306,  303,  307,  309,  310,  312,
      313,  314,  285,  316,  311,  286,  288,  303,  289,  290,
      311,  291,  317,  318,  292,  293,  295,  296,  297,  298,
      301,  302,  304,  306,  303,  307,  309,  310,  312,  313,

      314,  319,  316,  311,  320,  321,  303,  322,  323,  311,
      324,  317,  318,  325,  326,  327,  328,  329,  330,  331,
      332,  333,  338,  340,  342,  343,  344,  346,  347,  348,
      319,  349,  350,  320,  321,  351,  322,  323,  352,  324,
      353,  354,  325,  326,  327,  328,  329,  330,  331,  332,
      333,  338,  340,  342,  343,  344,  346,  347,  348,  357,
      349,  350,  358,  359,  351,  361,  362,  352,  363,  353,
      354,  364,  365,  367,  368,  369,  370,  371,  372,  374,
      375,  378,  380,  381,  382,  384,  385,  390,  357,  394,
      395,  358,  359,  396,  361,  362,  398,  363,  400,  401,

      364,  365,  367,  368,  369,  370,  371,  372,  374,  375,
      378,  380,  381,  382,  384,  385,  390,  402,  394,  395,
      403,  404,  396,  407,  411,  398,  412,  400,  401,  414,
      417,  418,  422,  423,  425,  426,  428,  430,  431,  434,
      435,  437,  438,  440,  441,  443,  402,  447,  448,  403,
      404,  449,  407,  411,  451,  412,  453,  455,  414,  417,
      418,  422,  423,  425,  426,  428,  430,  431,  434,  435,
      437,  438,  440,  441,  443,  459,  447,  448,  460,  464,
      449,    0,    0,  451,    0,  453,  455,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,  459,    0,    0,  460,  464,  467,
      467,  467,  467,  467,  467,  467,  468,  468,  468,  468,
      468,  468,  468,  469,  469,  469,  469,  469,  469,  469,
      471,  471,  472,    0,    0,  472,  472,  472,  472,  473,
      473,  473,  473,  473,  473,  473,  474,    0,  474,    0,
      474,  474,  474,  475,  475,  475,  475,  475,  475,  475,
      476,    0,  476,  476,  476,  476,  477,  477,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,

      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466,  466,  466,  466,  466,  466,  466,
      466,  466,  466,  466
    } ;

static yyconst flex_int16_t yy_rule_linenum[146] =
    {   0,
       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,   70,   71,   72,   73,
       74,   75,   76,   77,   78,   79,   80,   81,   82,   83,
       84,   85,   86,   87,   88,   89,   90,   91,   92,   93,
       94,   95,   96,   97,   98,   99,  100,  101,  102,  103,
      104,  105,  106,  107,  108,  109,  110,  111,  112,  113,
      114,  115,  116,  117,  118,  119,  120,  121,  122,  123,
      124,  125,  126,  127,  128,  129,  130,  131,  132,  133,

      134,  135,  136,  137,  138,  139,  140,  141,  142,  144,
      145,  146,  147,  148,  149,  150,  151,  152,  153,  154,
      155,  156,  160,  161,  162,  163,  164,  165,  166,  172,
      173,  177,  178,  179,  180,  181,  182,  183,  189,  190,
      194,  200,  201,  202,  203
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
#line 7 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
	#include "sql_parser.hpp"	//包含由parser.l生成的头文件
	#include "sql_scanner.h" 	//包含yyFlexLexer子类的头文件
	#include "location.hh" 	//包含位置调试信息头文件
	#include <string>
	# define YY_USER_ACTION  loc.columns (yyleng);
	#define yyterminate() return CatDB::SqlParser::make_END(loc);
	# undef yywrap
  	# define yywrap() 1
	#define YY_NO_UNISTD_H



#line 912 "/home/lighthouse/CatDB/sql/parser/sql_scanner.cpp"

#define INITIAL 0
#define beg_str 1
#define beg_str2 2
#define beg_ident 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#include <unistd.h>
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */
/* %if-bison-bridge */
/* %endif */
/* %not-for-header */

/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */

/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */
/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define ECHO LexerOutput( yytext, yyleng )
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
\
/* %if-c++-only C++ definition \ */\
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#define YY_FATAL_ERROR(msg) LexerError( msg )
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */

/* %ok-for-header */

/* %not-for-header */

/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define YY_DECL int yyFlexLexer::yylex()
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
/* %% [7.0] user's declarations go here */
#line 32 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"


#line 1075 "/home/lighthouse/CatDB/sql/parser/sql_scanner.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyin = & std::cin;
/* %endif */

		if ( ! yyout )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyout = & std::cout;
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 467 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 969 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				std::cerr << "--scanner backing up\n";
			else if ( yy_act < 146 )
				std::cerr << "--accepting rule at line " << yy_rule_linenum[yy_act] <<
				         "(\"" << yytext << "\")\n";
			else if ( yy_act == 146 )
				std::cerr << "--accepting default rule (\"" << yytext << "\")\n";
			else if ( yy_act == 147 )
				std::cerr << "--(end of buffer or a NUL)\n";
			else
				std::cerr << "--EOF (start condition " << YY_START << ")\n";
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 34 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_BOOL(loc); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 35 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_NULLX(loc); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 36 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_FALSE(loc); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 37 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_TRUE(loc); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 38 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_EXCEPT(loc); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 39 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_UNION(loc); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 40 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_INTERSECT(loc); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 41 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_OR(loc); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 42 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_AND(loc); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 43 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_NOT(loc); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 44 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_CMP_NE(loc); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_CMP_NE(loc); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 46 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_CMP_GE(loc); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 47 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_CMP_GT(loc); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 48 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_CMP_EQ(loc); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 49 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_CMP_LT(loc); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 50 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_CMP_LE(loc); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 51 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_LIKE(loc); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 52 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_BETWEEN(loc); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 53 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_ANALYZE(loc); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 54 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_IN(loc); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 55 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_IS(loc); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 56 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_ANY(loc); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 57 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_ALL(loc); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 58 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_AS(loc); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 59 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_ASC(loc); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 60 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_BY(loc); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 61 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_COLUMN(loc); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 62 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_COLUMNS(loc); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 63 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_CREATE(loc); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 64 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_DATABASE(loc); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 65 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_DATABASES(loc); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_DATE(loc); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 67 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_DATETIME(loc); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 68 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_DELETE(loc); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 69 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_DESC(loc); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 70 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_DESCRIBE(loc); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 71 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_DISTINCT(loc); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 72 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_DOUBLE(loc); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 73 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_DROP(loc); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 74 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_DUAL(loc); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 75 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_EXISTS(loc); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 76 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_EXPLAIN(loc); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 77 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_FLOAT(loc); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 78 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_FROM(loc); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 79 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_FULL(loc); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 80 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_GROUP(loc); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 81 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_HAVING(loc); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 82 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_KILL(loc); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 83 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_IF(loc); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 84 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_INSERT(loc); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 85 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_INDEX(loc); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 86 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_INNER(loc); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 87 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_INT(loc); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 88 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_INTO(loc); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 89 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_JOIN(loc); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 90 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_LEFT(loc); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 91 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_LIMIT(loc); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 92 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_MEMORY(loc); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 93 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_NUMBER(loc); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 94 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_ON(loc); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 95 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_ORDER(loc); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 96 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_PROCESSLIST(loc); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 97 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_RIGHT(loc); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 98 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_ROWID(loc); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 99 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_SAMPLE(loc); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 100 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_SELECT(loc); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 101 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_SET(loc); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 102 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_SHOW(loc); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 103 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_SIZE(loc); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 104 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_STATIS(loc); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 105 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_STATUS(loc); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 106 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_TABLE(loc); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 107 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_TABLES(loc); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 108 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_UPDATE(loc); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 109 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_USING(loc); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 110 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_VALUES(loc); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 111 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_VARCHAR(loc); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 112 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_WHERE(loc); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 113 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_TINYINT(loc); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 114 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_SMALLINT(loc); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 115 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_MEDIUMINT(loc); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 116 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_BIGINT(loc); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 117 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_DECIMAL(loc); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 118 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_NUMERIC_SYM(loc); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 119 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_REAL(loc); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 120 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_CHAR(loc); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 121 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_BINARY(loc); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 122 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_VARBINARY(loc); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 123 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_TIMESTAMP_SYM(loc); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 124 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_TIME(loc); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 125 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_CASE(loc); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 126 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_WHEN(loc); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 127 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_THEN(loc); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 128 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_ELSE(loc); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 129 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_END_SYM(loc); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 130 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_QB_NAME(loc); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 131 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_USE_HASH(loc); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 132 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_USE_NL(loc); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 133 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_LEADING(loc); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 134 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_PARALLEL(loc); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 135 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_ORDERED(loc); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 136 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_NO_REWRITE(loc); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 137 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_ENGINE(loc); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 138 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_INFILE(loc); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 139 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_FIELD(loc); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 140 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_LINE(loc); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 141 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_SPLIT(loc); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 142 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_CSV(loc); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 144 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_LP(loc); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 145 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_RP(loc); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 146 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_COMMA(loc); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 147 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_PERIOD(loc); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 148 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_SEMICOLON(loc); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 149 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_PLUS(loc); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 150 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_MINUS(loc); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 151 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_MUL(loc); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 152 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_DIV(loc); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 153 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_BEGIN_HINT(loc); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 154 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_END_HINT(loc); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 155 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{parse_str.clear();BEGIN(beg_str);}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 156 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{
						BEGIN(INITIAL);
						return CatDB::SqlParser::make_STRING(parse_str,loc);
					}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 160 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
parse_str += '\n';
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 161 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
parse_str += '\t';
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 162 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
parse_str += '\r';
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 163 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
parse_str += '\b';
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 164 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
parse_str += '\f';
	YY_BREAK
case 128:
/* rule 128 can match eol */
YY_RULE_SETUP
#line 165 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
parse_str += yytext[1];
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 166 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{
						tmp_ptr = yytext;
						while( *tmp_ptr )
							parse_str += *tmp_ptr++;
					}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 172 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{parse_str.clear();BEGIN(beg_str2);}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 173 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{
						BEGIN(INITIAL);
						return CatDB::SqlParser::make_STRING(parse_str,loc);
					}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 177 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
parse_str += '\n';
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 178 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
parse_str += '\t';
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 179 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
parse_str += '\r';
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 180 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
parse_str += '\b';
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 181 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
parse_str += '\f';
	YY_BREAK
case 137:
/* rule 137 can match eol */
YY_RULE_SETUP
#line 182 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
parse_str += yytext[1];
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 183 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{
						tmp_ptr = yytext;
						while( *tmp_ptr )
							parse_str += *tmp_ptr++;
					}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 189 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{parse_str.clear();BEGIN(beg_ident);}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 190 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{
						BEGIN(INITIAL);
						return CatDB::SqlParser::make_IDENT(parse_str,loc);
					}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 194 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{
						tmp_ptr = yytext;
						while( *tmp_ptr )
							parse_str += *tmp_ptr++;
					}
	YY_BREAK
case 142:
/* rule 142 can match eol */
YY_RULE_SETUP
#line 200 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"

	YY_BREAK
case 143:
YY_RULE_SETUP
#line 201 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_NUMERIC(yytext,loc);	}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 202 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_IDENT(yytext,loc);	} 
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 203 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ return CatDB::SqlParser::make_QB_NAME_IDENT(yytext+1,loc);	} 
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(beg_str):
case YY_STATE_EOF(beg_str2):
case YY_STATE_EOF(beg_ident):
#line 204 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
{ yyterminate(); }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 205 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"
ECHO;
	YY_BREAK
#line 1949 "/home/lighthouse/CatDB/sql/parser/sql_scanner.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = 0;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	CatDB_free(yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	CatDB_free(yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if ( new_in )
		{
		yy_delete_buffer( YY_CURRENT_BUFFER );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );
		}

	if ( new_out )
		yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout->write( buf, size );
}
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
int yyFlexLexer::yy_get_next_buffer()
/* %endif */
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					CatDB_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) CatDB_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */

/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_get_previous_state()
/* %endif */
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 467 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
/* %endif */
{
	register int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 467 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 466);

		return yy_is_jam ? 0 : yy_current_state;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyunput( int c, register char* yy_bp)
/* %endif */
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yyinput()
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyrestart( std::istream* input_file )
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_load_buffer_state()
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) CatDB_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) CatDB_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		CatDB_free((void *) b->yy_ch_buf  );

	CatDB_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_is_interactive = 0;
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypop_buffer_state (void)
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yyensure_buffer_stack(void)
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)CatDB_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)CatDB_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_push_state( int new_state )
/* %endif */
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) CatDB_alloc(new_size  );

		else
			(yy_start_stack) = (int *) CatDB_realloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_pop_state()
/* %endif */
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yy_top_state()
/* %endif */
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::LexerError( yyconst char msg[] )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* %if-reentrant */
/* %endif */
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *CatDB_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *CatDB_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void CatDB_free (void * ptr )
{
	free( (char *) ptr );	/* see CatDB_realloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 205 "/home/lighthouse/CatDB/sql/parser/sql_parser.l"



