#line 1 "D:/CatDB/parser/lex_yacc/sql_scanner.cpp"

#line 3 "D:/CatDB/parser/lex_yacc/sql_scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer CatDB_FlexLexer
/* %endif */

/* %if-c-only */
/* %endif */

#ifdef yyalloc
#define CatDB_alloc_ALREADY_DEFINED
#else
#define yyalloc CatDB_alloc
#endif

#ifdef yyrealloc
#define CatDB_realloc_ALREADY_DEFINED
#else
#define yyrealloc CatDB_realloc
#endif

#ifdef yyfree
#define CatDB_free_ALREADY_DEFINED
#else
#define yyfree CatDB_free
#endif

/* %if-c-only */
/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
/* %if-c-only */
/* %endif */

/* %if-c++-only */
	std::streambuf* yy_input_file;
/* %endif */

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */
/* %if-not-reentrant */
/* %not-for-header */
/* %ok-for-header */

/* %endif */
/* %endif */

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int SqlScanner::yylex()

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */
/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
/* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */\
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
/* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */\
	(yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 110
#define YY_END_OF_BUFFER 111
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[341] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  111,  110,
      107,  110,   86,   95,   77,   78,   84,   82,   79,   83,
       80,   85,  108,   81,   16,   15,   14,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  104,   94,   87,
      110,  103,   96,  110,  106,  105,  107,   11,  108,  108,
      108,    0,   17,   12,   13,  109,  109,  109,   25,  109,
      109,  109,   27,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,   21,   22,
      109,  109,  109,  109,    8,  109,  109,  109,  109,  109,

      109,  109,  109,  109,  109,  109,  109,  109,   94,   93,
       91,   92,   88,   90,   89,  103,  102,  100,  101,   97,
       99,   98,  106,    0,    0,    0,  108,   24,  109,    9,
       23,   26,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,   49,  109,  109,
      109,   10,  109,  109,  109,  109,  109,   55,  109,  109,
      109,  109,  109,  109,  109,  109,  109,   61,  109,  109,
      109,    0,  108,    0,  108,  109,  109,  109,  109,    1,
       72,  109,  109,  109,   32,  109,  109,   35,  109,  109,

       39,   40,  109,  109,  109,  109,  109,   44,  109,  109,
      109,  109,  109,   50,   18,  109,  109,    2,  109,  109,
      109,   71,  109,   56,  109,  109,  109,   76,  109,    4,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,    3,   43,   45,  109,   48,  109,  109,   51,
      109,  109,  109,   53,  109,  109,  109,   58,  109,  109,
        6,  109,  109,  109,  109,   64,  109,  109,   68,   73,
      109,   29,  109,  109,  109,   34,  109,  109,   38,    5,
       41,  109,   46,   47,  109,  109,   52,  109,   54,  109,

       57,   59,  109,  109,   60,   62,  109,  109,   20,   19,
       28,  109,  109,   69,  109,  109,   42,  109,  109,   70,
      109,  109,   65,  109,   63,   30,   33,   36,   37,  109,
      109,   66,  109,  109,   31,    7,   67,   75,   74,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    1,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,   16,   17,
       18,   19,    1,    1,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       29,   36,   37,   38,   39,   40,   41,   42,   43,   44,
        1,   45,    1,    1,   29,   46,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   29,   56,   57,   58,   59,
       60,   61,   29,   62,   63,   64,   65,   66,   67,   68,
       69,   70,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    1,    3,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    1,    1,    1,    1,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    2,    6,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5
    } ;

static const flex_int16_t yy_base[350] =
    {   0,
        0,    0,   68,   69,   72,   73,   74,   77,  211,  711,
       79,  163,  711,  711,  711,  711,  711,  711,  711,  711,
      141,  711,   70,  711,   68,  711,  135,   67,   82,  100,
      143,   47,  108,   67,   64,   72,    0,  104,  117,  104,
      104,  121,  159,  160,  115,  126,  130,  711,    0,  711,
      168,    0,  711,  193,    0,  711,   88,  711,  134,  185,
      220,   80,  711,  711,  711,    0,  130,  217,  153,  157,
      166,  178,    0,  204,  197,  210,  201,  225,  205,  204,
      212,  228,  248,  222,  224,  225,  229,  226,  257,    0,
      261,  227,  235,  269,  255,  261,  273,  253,  276,  278,

      281,  282,  251,  278,  289,  294,  300,  298,    0,  711,
      711,  711,  711,  711,  711,    0,  711,  711,  711,  711,
      711,  711,    0,   81,   87,  132,   97,    0,  293,    0,
        0,    0,  287,  304,  314,  307,  306,  304,  324,  327,
      318,  324,  330,  317,  332,  321,  327,  336,  326,  334,
      329,  347,  338,  333,  348,  353,  359,  361,  362,  360,
      362,    0,  362,  376,  375,  371,  381,    0,  366,  377,
      371,  380,  390,  373,  394,  386,  402,    0,  386,  408,
      400,   93,   92,   86,   82,  395,  399,  406,  404,    0,
        0,  411,  406,  410,  409,  416,  414,  417,  426,  428,

        0,    0,  425,  423,  435,  439,  429,    0,  433,  438,
      430,  439,  440,    0,    0,  439,  441,    0,  459,  452,
      453,    0,  462,    0,  460,  453,  471,  462,  468,    0,
      467,  466,  481,  479,  481,  485,  468,  489,  478,  476,
      487,  497,  504,  499,  508,  505,  503,  500,  513,  501,
      504,  515,    0,    0,    0,  518,    0,  509,  512,    0,
      518,  516,  525,    0,  519,  532,  525,  526,  528,  535,
        0,  545,  535,  541,  557,    0,  555,  548,    0,    0,
      545,    0,  547,  553,  555,    0,  569,  569,    0,    0,
        0,  560,    0,    0,  571,  569,    0,  577,    0,  568,

        0,    0,  582,  567,    0,    0,  583,  573,    0,    0,
        0,  589,  590,    0,  591,  582,    0,  594,  588,    0,
      585,  593,    0,  592,    0,  595,    0,    0,    0,  595,
      596,    0,  601,  594,    0,    0,    0,    0,    0,  711,
      663,  669,  675,   83,  681,  687,  693,  699,  705
    } ;

static const flex_int16_t yy_def[350] =
    {   0,
      340,    1,  341,  341,  342,  342,  343,  343,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  340,  345,  340,
      346,  347,  340,  348,  349,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  345,  340,
      340,  340,  340,  340,  340,  347,  340,  340,  340,  340,
      340,  340,  349,  340,  340,  340,  340,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  340,  340,  340,  340,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,    0,
      340,  340,  340,  340,  340,  340,  340,  340,  340
    } ;

static const flex_int16_t yy_nxt[782] =
    {   0,
       10,   11,   11,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   37,
       38,   39,   40,   41,   37,   42,   43,   44,   45,   46,
       47,   37,   37,   37,   10,   48,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       37,   42,   43,   44,   45,   46,   47,   37,   37,   37,
       10,   10,   50,   50,   10,   10,   10,   53,   53,   10,
       57,   57,   60,   88,   61,   63,   64,   66,   83,   57,
       57,  126,  182,   62,  127,  183,  185,   67,  184,   68,

      185,  185,   87,   69,   89,   70,  183,  183,   90,   71,
       88,  127,   51,   51,   83,   72,   54,   54,   10,   56,
       62,   10,   56,   67,   73,   68,   74,   84,   87,   69,
       89,   91,   70,   75,   90,   76,   71,   93,   85,   95,
       92,   72,   94,   86,   96,  107,  127,  104,   59,  105,
       73,  106,   65,   74,   84,   59,  108,  124,   91,   75,
      128,   76,   77,   93,   85,   95,   78,   92,   94,   86,
       79,   96,  107,  104,  132,  105,   80,  106,   81,  101,
       58,   82,   97,  108,  124,   98,  128,  102,  111,   77,
       99,  134,  112,   78,  133,  103,  100,   79,  135,   59,

      113,  132,   80,  114,   81,  115,  101,   82,  125,   97,
      340,  136,   98,  118,  102,  111,   99,  119,  134,  112,
      133,  103,  100,  137,  135,  120,  113,  138,  121,  114,
      122,  115,   60,  139,   61,  125,  129,  136,  140,  130,
      118,  144,  145,   62,  119,  146,  141,  147,  340,  161,
      137,  120,  151,  138,  121,  142,  122,  152,  153,  131,
      139,  143,  154,  129,  140,  155,  130,  144,  145,  148,
       62,  146,  162,  141,  147,  149,  161,  165,  151,  156,
      166,  142,  150,  152,  153,  131,  169,  143,  154,  175,
      159,  155,  160,  157,  158,  170,  148,  171,  162,  163,

      164,  172,  149,  167,  165,  176,  156,  166,  150,  340,
      168,  177,  169,  173,  174,  175,  159,  178,  160,  157,
      158,  181,  170,  186,  171,  163,  164,  187,  172,  167,
      179,  188,  176,  189,  340,  180,  168,  190,  177,  173,
      174,  191,  192,  193,  178,  196,  194,  197,  181,  186,
      195,  198,  200,  187,  199,  201,  179,  202,  188,  203,
      189,  180,  204,  190,  205,  206,  207,  191,  192,  208,
      193,  209,  196,  194,  197,  210,  211,  195,  198,  200,
      199,  201,  212,  202,  213,  215,  203,  216,  204,  217,
      205,  206,  218,  207,  214,  208,  219,  209,  221,  220,

      340,  222,  210,  211,  223,  340,  224,  225,  226,  212,
      227,  213,  215,  228,  216,  229,  217,  230,  218,  231,
      214,  232,  238,  219,  233,  221,  220,  222,  234,  235,
      243,  223,  224,  225,  226,  236,  227,  237,  239,  240,
      228,  229,  241,  242,  230,  231,  244,  245,  232,  238,
      233,  246,  247,  248,  252,  234,  235,  243,  249,  250,
      251,  236,  253,  237,  239,  240,  254,  255,  241,  242,
      256,  257,  244,  245,  258,  259,  260,  246,  247,  261,
      248,  252,  262,  265,  249,  250,  251,  263,  264,  253,
      266,  267,  254,  255,  268,  270,  256,  257,  269,  271,

      258,  259,  260,  272,  273,  261,  274,  275,  276,  262,
      265,  277,  278,  263,  264,  279,  266,  267,  280,  281,
      282,  268,  270,  283,  269,  271,  284,  285,  286,  272,
      287,  273,  288,  274,  275,  276,  289,  277,  290,  278,
      291,  279,  292,  293,  280,  281,  294,  282,  295,  296,
      283,  297,  298,  284,  285,  286,  299,  287,  288,  300,
      340,  301,  302,  289,  290,  303,  291,  304,  305,  292,
      293,  306,  294,  307,  295,  296,  308,  297,  309,  298,
      310,  311,  299,  312,  313,  314,  300,  301,  302,  315,
      316,  303,  317,  304,  318,  305,  319,  306,  320,  307,

      321,  322,  324,  308,  323,  309,  310,  311,  325,  312,
      313,  314,  326,  327,  328,  330,  315,  316,  317,  329,
      331,  318,  332,  319,  333,  320,  321,  334,  322,  324,
      323,  335,  336,  337,  325,  338,  339,  340,  340,  326,
      327,  328,  330,  340,  340,  329,  331,  340,  332,  340,
      333,  340,  340,  334,  340,  340,  340,  335,  336,  337,
      340,  338,  339,   49,   49,   49,   49,   49,   49,   52,
       52,   52,   52,   52,   52,   55,   55,   55,   55,   55,
       55,  109,  340,  340,  109,  109,  109,  110,  110,  110,
      110,  110,  110,  116,  340,  116,  340,  116,  116,  117,

      117,  117,  117,  117,  117,  123,  340,  123,  123,  123,
        9,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340
    } ;

static const flex_int16_t yy_chk[782] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    3,    4,    5,    6,    7,    5,    6,    8,
       11,   11,   23,   35,   23,   25,   25,  344,   32,   57,
       57,   62,  124,   23,   62,  124,  185,   28,  125,   28,

      184,  125,   34,   28,   36,   29,  183,  182,   36,   29,
       35,  127,    3,    4,   32,   29,    5,    6,    7,    7,
       23,    8,    8,   28,   29,   28,   30,   33,   34,   28,
       36,   38,   29,   30,   36,   30,   29,   40,   33,   41,
       39,   29,   40,   33,   42,   46,  126,   45,   59,   45,
       29,   45,   27,   30,   33,   21,   47,   59,   38,   30,
       67,   30,   31,   40,   33,   41,   31,   39,   40,   33,
       31,   42,   46,   45,   69,   45,   31,   45,   31,   44,
       12,   31,   43,   47,   59,   43,   67,   44,   51,   31,
       43,   71,   51,   31,   70,   44,   43,   31,   71,   60,

       51,   69,   31,   51,   31,   51,   44,   31,   60,   43,
        9,   72,   43,   54,   44,   51,   43,   54,   71,   51,
       70,   44,   43,   74,   71,   54,   51,   75,   54,   51,
       54,   51,   61,   76,   61,   60,   68,   72,   77,   68,
       54,   79,   80,   61,   54,   81,   78,   82,    0,   92,
       74,   54,   84,   75,   54,   78,   54,   85,   86,   68,
       76,   78,   87,   68,   77,   88,   68,   79,   80,   83,
       61,   81,   93,   78,   82,   83,   92,   95,   84,   89,
       96,   78,   83,   85,   86,   68,   98,   78,   87,  103,
       91,   88,   91,   89,   89,   99,   83,  100,   93,   94,

       94,  101,   83,   97,   95,  104,   89,   96,   83,    0,
       97,  105,   98,  102,  102,  103,   91,  106,   91,   89,
       89,  108,   99,  129,  100,   94,   94,  133,  101,   97,
      107,  134,  104,  135,    0,  107,   97,  136,  105,  102,
      102,  137,  138,  139,  106,  141,  140,  142,  108,  129,
      140,  143,  145,  133,  144,  146,  107,  147,  134,  148,
      135,  107,  149,  136,  150,  151,  152,  137,  138,  153,
      139,  154,  141,  140,  142,  155,  156,  140,  143,  145,
      144,  146,  157,  147,  158,  159,  148,  160,  149,  161,
      150,  151,  163,  152,  158,  153,  164,  154,  165,  164,

        0,  166,  155,  156,  167,    0,  169,  170,  171,  157,
      172,  158,  159,  173,  160,  174,  161,  175,  163,  176,
      158,  177,  187,  164,  179,  165,  164,  166,  180,  180,
      194,  167,  169,  170,  171,  181,  172,  186,  188,  189,
      173,  174,  192,  193,  175,  176,  195,  196,  177,  187,
      179,  197,  198,  199,  205,  180,  180,  194,  200,  203,
      204,  181,  206,  186,  188,  189,  207,  209,  192,  193,
      210,  211,  195,  196,  212,  213,  216,  197,  198,  217,
      199,  205,  219,  223,  200,  203,  204,  220,  221,  206,
      225,  226,  207,  209,  227,  229,  210,  211,  228,  231,

      212,  213,  216,  232,  233,  217,  234,  235,  236,  219,
      223,  237,  238,  220,  221,  239,  225,  226,  240,  241,
      242,  227,  229,  243,  228,  231,  244,  245,  246,  232,
      247,  233,  248,  234,  235,  236,  249,  237,  250,  238,
      251,  239,  252,  256,  240,  241,  258,  242,  259,  261,
      243,  262,  263,  244,  245,  246,  265,  247,  248,  266,
        0,  267,  268,  249,  250,  269,  251,  270,  272,  252,
      256,  273,  258,  274,  259,  261,  275,  262,  277,  263,
      278,  281,  265,  283,  284,  285,  266,  267,  268,  287,
      288,  269,  292,  270,  295,  272,  296,  273,  298,  274,

      300,  303,  307,  275,  304,  277,  278,  281,  308,  283,
      284,  285,  312,  313,  315,  318,  287,  288,  292,  316,
      319,  295,  321,  296,  322,  298,  300,  324,  303,  307,
      304,  326,  330,  331,  308,  333,  334,    0,    0,  312,
      313,  315,  318,    0,    0,  316,  319,    0,  321,    0,
      322,    0,    0,  324,    0,    0,    0,  326,  330,  331,
        0,  333,  334,  341,  341,  341,  341,  341,  341,  342,
      342,  342,  342,  342,  342,  343,  343,  343,  343,  343,
      343,  345,    0,    0,  345,  345,  345,  346,  346,  346,
      346,  346,  346,  347,    0,  347,    0,  347,  347,  348,

      348,  348,  348,  348,  348,  349,    0,  349,  349,  349,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340
    } ;

static const flex_int16_t yy_rule_linenum[110] =
    {   0,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
       76,   77,   78,   79,   80,   81,   82,   83,   84,   85,
       86,   87,   88,   89,   90,   91,   92,   93,   94,   95,
       96,   97,   98,   99,  100,  101,  102,  103,  104,  105,
      106,  107,  108,  109,  110,  111,  113,  114,  115,  116,
      117,  118,  119,  120,  121,  123,  124,  128,  129,  130,
      131,  132,  133,  134,  140,  141,  145,  146,  147,  148,

      149,  150,  151,  157,  158,  162,  168,  169,  170
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "D:/CatDB/parser/lex_yacc/sql_parser.l"
#line 7 "D:/CatDB/parser/lex_yacc/sql_parser.l"
	#include "sql_parser.hpp"	//包含由parser.l生成的头文件
	#include "sql_scanner.h" 	//包含yyFlexLexer子类的头文件
	#include "location.hh" 	//包含位置调试信息头文件
	#include <string>
	# define YY_USER_ACTION  loc.columns (yyleng);
	#define yyterminate() CatDB::SqlParser::make_END(loc);
	# undef yywrap
  	# define yywrap() 1
	#define YY_NO_UNISTD_H
  	static CatDB::location loc;	//声明位置实例
	std::string parse_str;
	char* tmp_ptr;
#line 809 "D:/CatDB/parser/lex_yacc/sql_scanner.cpp"

#line 811 "D:/CatDB/parser/lex_yacc/sql_scanner.cpp"

#define INITIAL 0
#define beg_str 1
#define beg_str2 2
#define beg_ident 3

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */
/* %if-bison-bridge */
/* %endif */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */
/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define ECHO LexerOutput( yytext, yyleng )
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
/* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */\
\
/* %if-c++-only C++ definition \ */\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#define YY_FATAL_ERROR(msg) LexerError( msg )
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define YY_DECL int yyFlexLexer::yylex()
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP \
	YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyin.rdbuf(std::cin.rdbuf());
/* %endif */

		if ( ! yyout )
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			yyout.rdbuf(std::cout.rdbuf());
/* %endif */

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
/* %% [7.0] user's declarations go here */
#line 34 "D:/CatDB/parser/lex_yacc/sql_parser.l"


#line 1002 "D:/CatDB/parser/lex_yacc/sql_scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
/* %% [8.0] yymore()-related code goes here */
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

/* %% [9.0] code to set up and find next match goes here */
		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 341 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 711 );

yy_find_action:
/* %% [10.0] code to find the action number goes here */
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

/* %% [11.0] code for yylineno update goes here */

do_action:	/* This label is used only to access EOF actions. */

/* %% [12.0] debug code goes here */
		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				std::cerr << "--scanner backing up\n";
			else if ( yy_act < 110 )
				std::cerr << "--accepting rule at line " << yy_rule_linenum[yy_act] <<
				         "(\"" << yytext << "\")\n";
			else if ( yy_act == 110 )
				std::cerr << "--accepting default rule (\"" << yytext << "\")\n";
			else if ( yy_act == 111 )
				std::cerr << "--(end of buffer or a NUL)\n";
			else
				std::cerr << "--EOF (start condition " << YY_START << ")\n";
			}

		switch ( yy_act )
	{ /* beginning of action switch */
/* %% [13.0] actions go here */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_BOOL(loc); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_NULLX(loc); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_FALSE(loc); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_TRUE(loc); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_EXCEPT(loc); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_UNION(loc); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_INTERSECT(loc); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 43 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_OR(loc); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 44 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_AND(loc); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_NOT(loc); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 46 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_CMP_NE(loc); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 47 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_CMP_NE(loc); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 48 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_CMP_GE(loc); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_CMP_GT(loc); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_CMP_EQ(loc); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_CMP_LT(loc); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_CMP_LE(loc); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_LIKE(loc); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_BETWEEN(loc); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_ANALYZE(loc); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 56 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_IN(loc); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 57 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_IS(loc); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 58 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_ANY(loc); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 59 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_ALL(loc); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 60 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_AS(loc); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 61 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_ASC(loc); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 62 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_BY(loc); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 63 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_COLUMNS(loc); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 64 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_CREATE(loc); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 65 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_DATABASE(loc); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 66 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_DATABASES(loc); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 67 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_DATE(loc); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 68 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_DATETIME(loc); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 69 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_DELETE(loc); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 70 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_DESC(loc); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 71 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_DESCRIBE(loc); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 72 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_DISTINCT(loc); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 73 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_DOUBLE(loc); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 74 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_DROP(loc); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 75 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_DUAL(loc); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 76 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_EXISTS(loc); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 77 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_EXPLAIN(loc); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 78 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_FLOAT(loc); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 79 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_FROM(loc); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 80 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_GROUP(loc); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 81 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_HAVING(loc); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 82 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_INSERT(loc); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 83 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_INDEX(loc); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 84 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_INT(loc); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 85 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_INTO(loc); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 86 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_LIMIT(loc); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 87 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_NUMBER(loc); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 88 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_ORDER(loc); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 89 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_SELECT(loc); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 90 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_SET(loc); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 91 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_SHOW(loc); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 92 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_STATUS(loc); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 93 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_TABLE(loc); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 94 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_TABLES(loc); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 95 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_UPDATE(loc); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 96 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_USING(loc); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 97 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_VALUES(loc); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 98 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_VARCHAR(loc); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 99 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_WHERE(loc); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 100 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_TINYINT(loc); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 101 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_SMALLINT(loc); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 102 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_MEDIUMINT(loc); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 103 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_BIGINT(loc); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 104 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_DECIMAL(loc); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 105 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_NUMERIC_SYM(loc); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 106 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_REAL(loc); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 107 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_CHAR(loc); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 108 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_BINARY(loc); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 109 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_VARBINARY(loc); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 110 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_TIMESTAMP_SYM(loc); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 111 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_TIME(loc); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 113 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_LP(loc); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 114 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_RP(loc); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 115 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_COMMA(loc); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 116 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_PERIOD(loc); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 117 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_SEMICOLON(loc); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 118 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_PLUS(loc); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 119 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_MINUS(loc); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 120 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_MUL(loc); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 121 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_DIV(loc); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 123 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{parse_str.clear();BEGIN(beg_str);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 124 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{
						BEGIN(INITIAL);
						return CatDB::SqlParser::make_STRING(parse_str,loc);
					}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 128 "D:/CatDB/parser/lex_yacc/sql_parser.l"
parse_str += '\n';
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 129 "D:/CatDB/parser/lex_yacc/sql_parser.l"
parse_str += '\t';
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 130 "D:/CatDB/parser/lex_yacc/sql_parser.l"
parse_str += '\r';
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 131 "D:/CatDB/parser/lex_yacc/sql_parser.l"
parse_str += '\b';
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 132 "D:/CatDB/parser/lex_yacc/sql_parser.l"
parse_str += '\f';
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 133 "D:/CatDB/parser/lex_yacc/sql_parser.l"
parse_str += yytext[1];
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 134 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{
						tmp_ptr = yytext;
						while( *tmp_ptr )
							parse_str += *tmp_ptr++;
					}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 140 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{parse_str.clear();BEGIN(beg_str2);}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 141 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{
						BEGIN(INITIAL);
						return CatDB::SqlParser::make_STRING(parse_str,loc);
					}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 145 "D:/CatDB/parser/lex_yacc/sql_parser.l"
parse_str += '\n';
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 146 "D:/CatDB/parser/lex_yacc/sql_parser.l"
parse_str += '\t';
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 147 "D:/CatDB/parser/lex_yacc/sql_parser.l"
parse_str += '\r';
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 148 "D:/CatDB/parser/lex_yacc/sql_parser.l"
parse_str += '\b';
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 149 "D:/CatDB/parser/lex_yacc/sql_parser.l"
parse_str += '\f';
	YY_BREAK
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 150 "D:/CatDB/parser/lex_yacc/sql_parser.l"
parse_str += yytext[1];
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 151 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{
						tmp_ptr = yytext;
						while( *tmp_ptr )
							parse_str += *tmp_ptr++;
					}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 157 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{parse_str.clear();BEGIN(beg_ident);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 158 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{
						BEGIN(INITIAL);
						return CatDB::SqlParser::make_IDENT(parse_str,loc);
					}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 162 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{
						tmp_ptr = yytext;
						while( *tmp_ptr )
							parse_str += *tmp_ptr++;
					}
	YY_BREAK
case 107:
/* rule 107 can match eol */
YY_RULE_SETUP
#line 168 "D:/CatDB/parser/lex_yacc/sql_parser.l"

	YY_BREAK
case 108:
YY_RULE_SETUP
#line 169 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_NUMERIC(yytext,loc);	}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 170 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ return CatDB::SqlParser::make_IDENT(yytext,loc);	} 
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(beg_str):
case YY_STATE_EOF(beg_str2):
case YY_STATE_EOF(beg_ident):
#line 171 "D:/CatDB/parser/lex_yacc/sql_parser.l"
{ yyterminate(); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 172 "D:/CatDB/parser/lex_yacc/sql_parser.l"
ECHO;
	YY_BREAK
#line 1662 "D:/CatDB/parser/lex_yacc/sql_scanner.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
/* %if-c-only */
/* %endif */
/* %if-c++-only */
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
/* %endif */
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
/* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
int yyFlexLexer::yy_get_next_buffer()
/* %endif */
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_get_previous_state()
/* %endif */
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
/* %% [15.0] code to get the start state into yy_current_state goes here */
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
/* %% [16.0] code to find the next state goes here */
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 341 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
/* %endif */
{
	int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 341 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 340);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyunput( int c, char* yy_bp)
/* %endif */
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

/* %% [18.0] update yylineno here */

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
/* %if-c-only */
/* %endif */
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yyinput()
/* %endif */
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

/* %% [19.0] update BOL and yylineno */

	return c;
}
/* %if-c-only */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yyrestart( std::istream& input_file )
/* %endif */
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/* %if-c++-only */
/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
/* %endif */
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_load_buffer_state()
/* %endif */
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
/* %if-c-only */
/* %endif */
/* %if-c++-only */
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
/* %endif */
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
/* %endif */
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/* %if-c++-only */
/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )
/* %endif */

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_input_file = file.rdbuf();
/* %endif */
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

/* %if-c-only */
/* %endif */
/* %if-c++-only */
	b->yy_is_interactive = 0;
/* %endif */
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
/* %endif */
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
/* %endif */
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypop_buffer_state (void)
/* %endif */
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yyensure_buffer_stack(void)
/* %endif */
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_push_state( int _new_state )
/* %endif */
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    void yyFlexLexer::yy_pop_state()
/* %endif */
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
    int yyFlexLexer::yy_top_state()
/* %endif */
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* %if-reentrant */
/* %endif */
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 172 "D:/CatDB/parser/lex_yacc/sql_parser.l"

