DROP DATABASE IF EXISTS TPCH_CSV;
CREATE DATABASE TPCH_CSV;
CREATE TABLE TPCH_CSV.NATION(N_NATIONKEY  NUMERIC,
N_NAME       VARCHAR,
N_REGIONKEY  NUMERIC,
N_COMMENT    VARCHAR) ENGINE = CSV, INFILE = "tpch-date/nation.tbl", FIELD SPLIT BY "|", LINE SPLIT BY "\n";

CREATE TABLE TPCH_CSV.REGION(R_REGIONKEY  NUMERIC,
R_NAME       VARCHAR,
R_COMMENT    VARCHAR) ENGINE = CSV, INFILE = "tpch-date/region.tbl", FIELD SPLIT BY "|", LINE SPLIT BY "\n";

CREATE TABLE TPCH_CSV.PART(P_PARTKEY     NUMERIC,
P_NAME        VARCHAR,
P_MFGR        VARCHAR,
P_BRAND       VARCHAR,
P_TYPE        VARCHAR,
P_SIZE        NUMERIC,
P_CONTAINER   VARCHAR,
P_RETAILPRICE NUMERIC,
P_COMMENT     VARCHAR) ENGINE = CSV, INFILE = "tpch-date/part.tbl", FIELD SPLIT BY "|", LINE SPLIT BY "\n";

CREATE TABLE TPCH_CSV.SUPPLIER(S_SUPPKEY     NUMERIC,
S_NAME        VARCHAR,
S_ADDRESS     VARCHAR,
S_NATIONKEY   NUMERIC,
S_PHONE       VARCHAR,
S_ACCTBAL     NUMERIC,
S_COMMENT     VARCHAR) ENGINE = CSV, INFILE = "tpch-date/supplier.tbl", FIELD SPLIT BY "|", LINE SPLIT BY "\n";

CREATE TABLE TPCH_CSV.PARTSUPP(PS_PARTKEY     NUMERIC,
PS_SUPPKEY     NUMERIC,
PS_AVAILQTY    NUMERIC,
PS_SUPPLYCOST  NUMERIC ,
PS_COMMENT     VARCHAR) ENGINE = CSV, INFILE = "tpch-date/partsupp.tbl", FIELD SPLIT BY "|", LINE SPLIT BY "\n";

CREATE TABLE TPCH_CSV.CUSTOMER(C_CUSTKEY     NUMERIC,
C_NAME        VARCHAR,
C_ADDRESS     VARCHAR,
C_NATIONKEY   NUMERIC,
C_PHONE       VARCHAR,
C_ACCTBAL     NUMERIC  ,
C_MKTSEGMENT  VARCHAR,
C_COMMENT     VARCHAR) ENGINE = CSV, INFILE = "tpch-date/customer.tbl", FIELD SPLIT BY "|", LINE SPLIT BY "\n";

CREATE TABLE TPCH_CSV.ORDERS(O_ORDERKEY       NUMERIC,
O_CUSTKEY        NUMERIC,
O_ORDERSTATUS    VARCHAR,
O_TOTALPRICE     NUMERIC,
O_ORDERDATE      DATETIME,
O_ORDERPRIORITY  VARCHAR,
O_CLERK          VARCHAR,
O_SHIPPRIORITY   NUMERIC,
O_COMMENT        VARCHAR) ENGINE = CSV, INFILE = "tpch-date/orders.tbl", FIELD SPLIT BY "|", LINE SPLIT BY "\n";

CREATE TABLE TPCH_CSV.LINEITEM(L_ORDERKEY    NUMERIC,
L_PARTKEY     NUMERIC,
L_SUPPKEY     NUMERIC,
L_LINENUMBER  NUMERIC,
L_QUANTITY    NUMERIC,
L_EXTENDEDPRICE  NUMERIC,
L_DISCOUNT    NUMERIC,
L_TAX         NUMERIC,
L_RETURNFLAG  VARCHAR,
L_LINESTATUS  VARCHAR,
L_SHIPDATE    DATETIME,
L_COMMITDATE  DATETIME,
L_RECEIPTDATE DATETIME,
L_SHIPINSTRUCT VARCHAR,
L_SHIPMODE     VARCHAR,
L_COMMENT      VARCHAR) ENGINE = CSV, INFILE = "tpch-date/lineitem.tbl", FIELD SPLIT BY "|", LINE SPLIT BY "\n";

DROP DATABASE IF EXISTS TPCH;
CREATE DATABASE TPCH;
CREATE TABLE TPCH.NATION(N_NATIONKEY  NUMERIC,
N_NAME       VARCHAR,
N_REGIONKEY  NUMERIC,
N_COMMENT    VARCHAR);

CREATE TABLE TPCH.REGION(R_REGIONKEY  NUMERIC,
R_NAME       VARCHAR,
R_COMMENT    VARCHAR);

CREATE TABLE TPCH.PART(P_PARTKEY     NUMERIC,
P_NAME        VARCHAR,
P_MFGR        VARCHAR,
P_BRAND       VARCHAR,
P_TYPE        VARCHAR,
P_SIZE        NUMERIC,
P_CONTAINER   VARCHAR,
P_RETAILPRICE NUMERIC,
P_COMMENT     VARCHAR);

CREATE TABLE TPCH.SUPPLIER(S_SUPPKEY     NUMERIC,
S_NAME        VARCHAR,
S_ADDRESS     VARCHAR,
S_NATIONKEY   NUMERIC,
S_PHONE       VARCHAR,
S_ACCTBAL     NUMERIC,
S_COMMENT     VARCHAR);

CREATE TABLE TPCH.PARTSUPP(PS_PARTKEY     NUMERIC,
PS_SUPPKEY     NUMERIC,
PS_AVAILQTY    NUMERIC,
PS_SUPPLYCOST  NUMERIC ,
PS_COMMENT     VARCHAR);

CREATE TABLE TPCH.CUSTOMER(C_CUSTKEY     NUMERIC,
C_NAME        VARCHAR,
C_ADDRESS     VARCHAR,
C_NATIONKEY   NUMERIC,
C_PHONE       VARCHAR,
C_ACCTBAL     NUMERIC  ,
C_MKTSEGMENT  VARCHAR,
C_COMMENT     VARCHAR);

CREATE TABLE TPCH.ORDERS(O_ORDERKEY       NUMERIC,
O_CUSTKEY        NUMERIC,
O_ORDERSTATUS    VARCHAR,
O_TOTALPRICE     NUMERIC,
O_ORDERDATE      DATETIME,
O_ORDERPRIORITY  VARCHAR,
O_CLERK          VARCHAR,
O_SHIPPRIORITY   NUMERIC,
O_COMMENT        VARCHAR);

CREATE TABLE TPCH.LINEITEM(L_ORDERKEY    NUMERIC,
L_PARTKEY     NUMERIC,
L_SUPPKEY     NUMERIC,
L_LINENUMBER  NUMERIC,
L_QUANTITY    NUMERIC,
L_EXTENDEDPRICE  NUMERIC,
L_DISCOUNT    NUMERIC,
L_TAX         NUMERIC,
L_RETURNFLAG  VARCHAR,
L_LINESTATUS  VARCHAR,
L_SHIPDATE    DATETIME,
L_COMMITDATE  DATETIME,
L_RECEIPTDATE DATETIME,
L_SHIPINSTRUCT VARCHAR,
L_SHIPMODE     VARCHAR,
L_COMMENT      VARCHAR);

INSERT INTO TPCH.NATION SELECT * FROM TPCH_CSV.NATION;
INSERT INTO TPCH.REGION SELECT * FROM TPCH_CSV.REGION;
INSERT INTO TPCH.PART SELECT * FROM TPCH_CSV.PART;
INSERT INTO TPCH.SUPPLIER SELECT * FROM TPCH_CSV.SUPPLIER;
INSERT INTO TPCH.PARTSUPP SELECT * FROM TPCH_CSV.PARTSUPP;
INSERT INTO TPCH.CUSTOMER SELECT * FROM TPCH_CSV.CUSTOMER;
INSERT INTO TPCH.ORDERS SELECT * FROM TPCH_CSV.ORDERS;
INSERT INTO TPCH.LINEITEM SELECT * FROM TPCH_CSV.LINEITEM;
